<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="DESKTOP-QD3OHAN" failures="1" tests="3" name="Test1" time="0.114" errors="0" timestamp="2021-08-09T23:23:31 IST">
  <testcase classname="Test1.Class1" name="ThirdClass" time="0.019">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test1.Class1.ThirdClass(Class1.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ThirdClass -->
  <testcase classname="Test1.Class2" name="FourthClass" time="0.003"/>
  <testcase classname="Test1.Class3" name="NinthClass" time="0.006"/>
  <testcase classname="Test1.Class2" name="SixthClass" time="0.0">
    <ignored/>
  </testcase> <!-- SixthClass -->
  <testcase classname="Test1.Class3" name="EightClass" time="0.0">
    <ignored/>
  </testcase> <!-- EightClass -->
  <testcase classname="Test1.Class2" name="FiveClass" time="0.0">
    <ignored/>
  </testcase> <!-- FiveClass -->
  <testcase classname="Test1.Class1" name="FirstClass" time="0.0">
    <ignored/>
  </testcase> <!-- FirstClass -->
  <testcase classname="Test1.Class3" name="SeventhClass" time="0.0">
    <ignored/>
  </testcase> <!-- SeventhClass -->
  <testcase classname="Test1.Class1" name="SecondClass" time="0.0">
    <ignored/>
  </testcase> <!-- SecondClass -->
</testsuite> <!-- Test1 -->
